#!/usr/bin/env bash

set -e

if [[ -n "${DEBUG}" ]]; then
    set -x
fi

drupal_ver=$1

url="https://raw.githubusercontent.com/drupal/drupal/${drupal_ver}/sites/default/default.settings.php"

array=(
    "./orig/default.settings.php::${url}"
)

outdated=0

for index in "${array[@]}" ; do
    local="${index%%::*}"
    url="${index##*::}"

    orig="/tmp/${RANDOM}"
    wget -qO "${orig}" "${url}"

    echo "Checking ${local}"

    if diff --strip-trailing-cr "${local}" "${orig}"; then
        echo "OK"
    else
        echo "!!! OUTDATED"
        echo "${remote}"
        outdated=1
    fi

    rm -f "${orig}"
done

[[ "${outdated}" == 0 ]] || exit 1