name: push
description: combine multi-arch image and push
inputs:
  version:
    description: version
    required: true
  php:
    description: php version
    required: true
  workdir:
    description: workdir
    required: true
  latest:
    description: if tag latest
    required: false
  latest_major:
    description: if tag latest major version
    required: false
  latest_php:
    description: if provided php version is latest
    required: false
  latest_major_php:
    description: if provided php version is latest major
    required: false
runs:
  using: "composite"
  steps:
    - name: Build image
      env:
        DRUPAL_VER: ${{ inputs.version }}
        PHP_VER: ${{ inputs.php }}
        LATEST: ${{ inputs.latest }}
        LATEST_MAJOR: ${{ inputs.latest_major }}
        LATEST_PHP: ${{ inputs.latest_php }}
        LATEST_MAJOR_PHP: ${{ inputs.latest_major_php }}
      run: |
        . $GITHUB_ACTION_PATH/release.sh
      shell: bash
      working-directory: ${{ inputs.workdir }}
